import { IProduct } from "../../types/product";

export const productList: IProduct[] = [
    {
        name: "Areia Sanitária Perfumada Campestre Pipicat - 4kg",
        image: "https://www.petlove.com.br/images/products/260066/mobile_shelf/Areia_Sanit%C3%A1ria_Kelco_Pipicat_Campestre_-_4_Kg_31023653_0002_1.jpg?1659549511",
        description: "Areia Sanitária Perfumada Campestre Pipicat - 4kg",
        price: 18.9,
        id: '1',
        quantity: 0,
    },
    {
        name: "Ração Úmida Whiskas Sachê Carne ao Molho para Gatos Adultos Castrados - 85 g",
        image: "https://www.petlove.com.br/images/products/231785/mobile_shelf/Ra%C3%A7%C3%A3o_%C3%9Amida_Whiskas_Sach%C3%AA_Carne_ao_Molho_para_Gatos_Adultos_Castrados_2032067.jpg?1627743377",
        description: "Ração Úmida Whiskas Sachê Carne ao Molho para Gatos Adultos Castrados - 85 g",
        price: 2.99,
        id: '2',
        quantity: 0,
    },
    {
        name: "Brinquedo LCM Bolinha com Penas Cat Toy Azul para Gato - Azul",
        image: "https://www.petlove.com.br/images/products/199620/mobile_shelf/Brinquedo_Bolinha_LCM_Pet's_Toys_Cat_-_Azul_1951311.jpg?1627641110",
        description: "Brinquedo LCM Bolinha com Penas Cat Toy Azul para Gato - Azul",
        price: 5.99,
        id: '3',
        quantity: 0,
    },
    {
        name: "Ração Seca PremieR Pet Golden Gatos Adultos Castrados Frango",
        image: "https://www.petlove.com.br/images/products/213107/mobile_shelf/Ra%C3%A7%C3%A3o_Golden_Gatos_Adultos_Castrados_Frango_31017079_3kg_lateral.jpg?1627684380",
        description: "Ração Seca PremieR Pet Golden Gatos Adultos Castrados Frango - 3 kg.",
        price: 67.9,
        id: '4',
        quantity: 0,
    },
    {
        name: "Ração Total Equilíbrio para Gatos Castrados Adultos de 1 A 7 Anos - 7,5 Kg",
        image: "https://www.petlove.com.br/images/products/189580/mobile_shelf/Ra%C3%A7%C3%A3o-Total-Equil%C3%ADbrio-para-Gatos-Castrados-Adultos-de-1-A-7-Anos.jpg?1627612262",
        description: "Ração Total Equilíbrio para Gatos Castrados Adultos de 1 A 7 Anos - 7,5 Kg",
        price: 233.99,
        id: '5',
        quantity: 0,
    },
    {
        name: "Brinquedo LCM Varinha Cat Collors Azul para Gato - Azul",
        image: "https://www.petlove.com.br/images/products/199940/mobile_shelf/Brinquedo_LCM_Cat_Collors_-_Azul_1951823.jpg?1627642230",
        description: "Brinquedo LCM Varinha Cat Collors Azul para Gato - Azul",
        price: 16.49,
        id: '6',
        quantity: 0,
    },
    {
        name: "Petisco Whiskas Temptations Antibola de Pelo para Gatos Adultos - 40 g",
        image: "https://www.petlove.com.br/images/products/186423/small/Whiskas_Petisco_Temptations_AntiBoladePelo_3100683.jpg?1627604717",
        description: "Petisco Whiskas Temptations Antibola de Pelo para Gatos Adultos - 40 g",
        price: 10.99,
        id: '7',
        quantity: 0,
    },
    {
        name: "Areia Sanitária Chalesco Micro Cristais de Sílica - 1,8Kg",
        image: "https://www.petlove.com.br/images/products/235184/small/Microcristais.jpg?1627754453",
        description: "Areia Sanitária Chalesco Micro Cristais de Sílica - 1,8Kg",
        price: 51.9,
        id: '8',
        quantity: 0,
    },
    {
        name: "Antipulgas e Carrapatos Frontline Plus para Gatos - 1 Unidade",
        image: "https://www.petlove.com.br/images/products/227448/small/Antipulgas_e_Carrapatos_Frontline_Plus_para_Gatos_3105713.jpg?1627727283",
        description: "Antipulgas e Carrapatos Frontline Plus para Gatos - 1 Unidade",
        price: 44.63,
        id: '9',
        quantity: 0,
    },
    {
        name: "Ração Úmida Pet Delícia Natural Picadinho de Carne para Gatos - 320 g",
        image: "https://www.petlove.com.br/images/products/249967/small/Ra%C3%A7%C3%A3o_%C3%9Amida_Pet_Del%C3%ADcia_Natural_Picadinho_de_Carne_para_Gatos_-_320_g_1210392_%284%29.jpg?1635447791",
        description: "Ração Úmida Pet Delícia Natural Picadinho de Carne para Gatos - 320 g",
        price: 20.99,
        id: '10',
        quantity: 0,
    },
    {
        name: "Fonte Bebedouro Amicus Aqua Mini Bivolt - Vermelha",
        image: "https://www.petlove.com.br/images/products/225530/small/Fonte_Bebedouro_Amicus_Aqua_Mini_Bivolt_Vermelha_1994061.jpg?1627723354",
        description: "Fonte Bebedouro Amicus Aqua Mini Bivolt - Vermelha",
        price: 110.42,
        id: '11',
        quantity: 0,
    },
    {
        name: "Bandeja Higiênica Furacão Pet Classic Preta para Gatos - Tam. Único",
        image: "https://www.petlove.com.br/images/products/180988/small/311712_1.jpg?1627592652",
        description: "Bandeja Higiênica Furacão Pet Classic Preta para Gatos - Tam. Único",
        price: 22.90,
        id: '12',
        quantity: 0,
    },
]

      